# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-08 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_information1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='project_information2',
            field=models.TextField(blank=True),
        ),
    ]
